In [16]:
# Logistic Regression

In [17]:
# Importing all the required Libraries

In [18]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score,recall_score, f1_score

In [19]:
# Loading the data and exploring it

In [20]:
data=pd.read_csv('diabetes_prediction_dataset.csv')
x=data[["age","hypertension","heart_disease","bmi","HbA1c_level","blood_glucose_level"]]
y=data["diabetes"]

In [21]:
# Training and testing the loaded datasets

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train.mean()

np.float64(2.0863311078755942e-16)

In [23]:
# Calculating the Accuracy, Precision, Recall and F1 score
# model

In [24]:
model=LogisticRegression(max_iter=200)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy:{accuracy}")
precision = precision_score(y_test, y_pred)
print(f"Precision:{precision}")
recall = recall_score(y_test,y_pred)
print(f"Recall:{recall}")
f1=f1_score(y_test , y_pred)
print(f"F1_score:{f1}")

[0 0 0 ... 0 0 0]
Accuracy:0.95875
Precision:0.8639736191261336
Recall:0.6135831381733021
F1_score:0.7175624786032181


In [25]:
# Threshold - changing the threshold changes the balance between precision and recall

In [26]:
p=model.predict_proba(x_test)[:,1]
print(p)
threshoold=0.8
y_pred=(p>=threshoold).astype(int)
y_pred

[0.00086679 0.00016224 0.00074995 ... 0.00031737 0.13299735 0.00863795]


array([0, 0, 0, ..., 0, 0, 0])

In [27]:
# Calculating the Accuracy, Precision, Recall and F1 score by using threshold

In [28]:
print("Accuracy", accuracy_score(y_test,y_pred))
print("Precision",precision_score(y_test,y_pred))
print("Recall", recall_score(y_test,y_pred))
print("F1_score", f1_score(y_test,y_pred))

Accuracy 0.95285
Precision 0.9716399506781751
Recall 0.4613583138173302
F1_score 0.6256450972608177
