In [ ]:
 # NumPy Basics
  # Numpy Array is a data structure used to perform mathematical operations

In [ ]:
import numpy as np

In [ ]:
numbers = [1,2,3,4,5]
numbers2=[6,7,8,9,10]
arr = np.array(numbers)
arr2= np.array(numbers2)
print(arr)
print(arr2)
print(type(numbers))
print(type(arr))
print(arr+10)

[1 2 3 4 5]
[ 6  7  8  9 10]
<class 'list'>
<class 'numpy.ndarray'>
[11 12 13 14 15]


In [ ]:
flat_sizes = np.array([650,820,500,100,940])
prices_lakh = np.array([55.0,72.0,40.0,98.0,85.0])
new_price = prices_lakh*1.08
print(new_price)
registration = ([2,2,2,2,2])
total_price = new_price + registration
print(total_price)

# .shape gives the Number of rows and columns of an Array.
print(flat_sizes.shape)

# .ndim gives the number of dimensions of an Array.
print(flat_sizes.ndim)

# .size gives the total number of elements in an Array.
print(flat_sizes.size)

# .dtype gives the data type of the elements in an Array.
print(flat_sizes.dtype)

[ 59.4   77.76  43.2  105.84  91.8 ]
[ 61.4   79.76  45.2  107.84  93.8 ]
(5,)
1
5
int64


In [ ]:
# each row is one flat : [size in sq ft , age in years]
flats_table = np.array([[650,8] , [820,3] , [500 , 15] , [1100 , 1]])
print(flats_table.shape)
zeros = np.ones((3,2))
# np.ones return a new array of given shape and type, filled with one
print(zeros)

counting = np.arange(0,10,2)
# np.arange() creates an Array with evenly spaced values within a given range
print(counting)


(4, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]


In [ ]:
counting = np.arange(0,100,12)
print(counting)

spread = np.linspace(0,100,6)
# np.linespace creates an array with evenly spaced numbers between a specified start and end value.
print(spread)

[ 0 12 24 36 48 60 72 84 96]
[  0.  20.  40.  60.  80. 100.]


In [ ]:
print("first size :" , flat_sizes[-1])
print("first size :" , flat_sizes[2:4])
print("first size :" , flat_sizes[:4])

first size : 940
first size : [500 100]
first size : [650 820 500 100]


In [ ]:
prices_lakh = np.array([55.0,72.0,40.0,98.0,85.0])
print(np.mean(prices_lakh))
# np.mean()  Returns the average (mean) value of an array.

print(np.max(prices_lakh))
# np.max()  Returns the maximum value in an array.

print(np.min(prices_lakh))
# np.min() Returns the minimum value in an array.

print(np.std(prices_lakh))
# np.std()  Returns the standard deviation of the values in an array.


70.0
98.0
40.0
20.67849124090053


In [ ]:
random = np.random.randint(0,256,(2,2))
print(random)

[[ 74  78]
 [225 119]]
